version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres-docker
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '15432:5432'
