version: '3.9'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-docker
    ports:
      - 19042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cluster