version: '3.8'
services:
  web:
    build: .
    ports:
      - "18080:8080"
      - "10022:22"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          cpus: '2'
          memory: 2048M